#define LOCAL_ERR_noError "Нет ошибки?"
#define LOCAL_ERR_errorNumber "Ошибка "
#define LOCAL_ERR_atLocation " в "
#define LOCAL_ERR_moreInfo ". Подробности:\n"
#define LOCAL_BOT_gameNotFound "Игра не найдена, пробую снова..."
#define LOCAL_BOT_gameFirstBrownTabFoundAt "Левый верхний угол первой коричневой вкладки найден в координатах "  
#define LOCAL_BOT_gameIsLost "Игра потеряна, пробую наёти её снова..."
#define LOCAL_BOT_botIsStopping "Бот останавливается..."
#define LOCAL_UI_initialStatus "Нажми кнопку выше и кликни по окну с игрой для старта"
#define LOCAL_UI_sleepTime "Пауза между рывками (мс.)"
#define LOCAL_UI_start "Запустить бота"
#define LOCAL_UI_stop "Остановить бота"
#define LOCAL_UI_latency "Пауза между рывками"
#define LOCAL_UI_updateWindowsList "Обновить список окон"
#define LOCAL_UI_appName "CFLF"
